Repository JNU-econovation/econo-techblog, pull requests merged in 2022-07, with the labels that each got.

#34 [Post Page] 좋아요 버튼 추가 및 댓글 리스트 렌더링 코드 수정
  fe/src/Post/Post.jsx
  fe/src/Post/components/CommentList.jsx
  fe/src/Post/components/Liked.jsx
  fe/src/Post/css/Comment.css
  fe/src/Post/css/CommentList.css
  fe/src/Post/css/Liked.css
  fe/src/Post/css/Post.css
Labels: frontend

#36 [Tech/Culture/Trouble Shooting 페이지] 레이아웃 및 css 구현
  fe/src/Tech/Tech.jsx
  fe/src/Tech/components/Banner.jsx
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Pagination.jsx
  fe/src/Tech/components/PostDetails.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/components/Tags.jsx
  fe/src/Tech/css/Banner.css
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Pagination.css
  fe/src/Tech/css/PostDetails.css
  fe/src/Tech/css/Recent.css
  fe/src/Tech/css/Tags.css
  fe/src/Tech/css/Tech.css
  fe/src/Tech/img/day.png
  fe/src/Tech/img/feather_eye.png
  fe/src/Tech/img/heart.png
Labels: frontend

#37 test : PostFetchMutationResolver All Function Test
  tcono/build.gradle
  tcono/src/main/resources/graphql/schema.graphqls
  tcono/src/test/java/blog/econovation/tcono/post/PostResolverTest.java
  tcono/src/test/java/blog/econovation/tcono/user/UserResolverTest.java
Labels: backend

#44 [Tech/Culture/Trouble Shooting 페이지] Pagination 구현 및 CSS 수정
  fe/package-lock.json
  fe/package.json
  fe/src/Tech/Tech.jsx
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Pagination.jsx
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Pagination.css
  fe/src/Tech/css/Tech.css
Labels: frontend

#53 [PR] 게시물 작성 페이지 구현
  fe/src/Write/HashtagInput.jsx
  fe/src/Write/Write.jsx
  fe/src/Write/css/HashtagInput.css
Labels: frontend

#54 [Post 페이지] 댓글작성 컴포넌트 추가
  fe/src/Post/Post.jsx
  fe/src/Post/components/CommentBox.jsx
  fe/src/Post/components/CommentList.jsx
  fe/src/Post/css/Comment.css
  fe/src/Post/css/CommentBox.css
  fe/src/Post/css/CommentList.css
  fe/src/Post/css/Liked.css
  fe/src/Post/css/Post.css
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Partition.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Partition.css
  fe/src/Tech/css/Recent.css
Labels: frontend

#57 [PR] 글작성 페이지 - 제목, 게시판
  fe/package-lock.json
  fe/package.json
  fe/src/Write/CategorySelectBox.jsx
  fe/src/Write/HashtagInput.jsx
  fe/src/Write/TitleInput.jsx
  fe/src/Write/Write.jsx
  fe/src/Write/css/HashtagInput.css
  fe/src/Write/css/TitleInput.css
Labels: frontend

#58 [Find Information Page] 아이디 찾기 페이지
  fe/src/FindInfo/FindId.jsx
  fe/src/FindInfo/FindIdBtn.jsx
  fe/src/FindInfo/FindInfo.jsx
  fe/src/FindInfo/FindInfoBox.jsx
  fe/src/FindInfo/SuccessFindId.jsx
  fe/src/FindInfo/css/FindIdBtn.css
  fe/src/FindInfo/css/FindInfo.css
  fe/src/FindInfo/css/FindInfoBox.css
  fe/src/FindInfo/css/SuccessFindId.css
  fe/src/FindInfo/img/check_circle.png
  fe/src/SignUp/SignUpBox.jsx
  fe/src/components/CardinalSelectBox.jsx
  fe/src/components/css/CardinalSelectBox.css
Labels: frontend

#63 [Post 페이지] 디자인 변경 및 추가된 기능 구현
  fe/src/Post/components/Comment.jsx
  fe/src/Post/components/CommentBox.jsx
  fe/src/Post/components/Liked.jsx
  fe/src/Post/components/PostInfo.jsx
  fe/src/Post/components/SelectBox.jsx
  fe/src/Post/css/Comment.css
  fe/src/Post/css/CommentBox.css
  fe/src/Post/css/Liked.css
  fe/src/Post/css/PostInfo.css
  fe/src/Post/css/SelectBox.css
  fe/src/Post/img/clickheart.png
  fe/src/Post/img/edit.png
  fe/src/Post/img/no_img.png
  fe/src/Post/img/trash.png
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Recent.css
  fe/src/Tech/img/no_img.png
  fe/src/components/Partition.jsx
  fe/src/components/PostDetails.jsx
  fe/src/components/css/Partition.css
  fe/src/components/css/PostDetails.css
Labels: frontend

#59 feat : postQuery/Mutation
  tcono/src/main/java/blog/econovation/tcono/domain/BaseTimeEntity.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/Category.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/CategoryRepository.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/MainCategory.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/Post.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/PostMutationResolver.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/PostQueryResolver.java
  tcono/src/main/java/blog/econovation/tcono/domain/post/PostRepository.java
  tcono/src/main/java/blog/econovation/tcono/web/dto/PostCreateRequestDto.java
  tcono/src/main/java/blog/econovation/tcono/web/dto/PostCreateResponseDto.java
  tcono/src/main/java/blog/econovation/tcono/web/dto/PostUpdateRequestDto.java
  tcono/src/main/java/blog/econovation/tcono/web/dto/PostUpdateResponseDto.java
  tcono/src/main/resources/graphql/schema.graphqls
Labels: backend

#69 [관리자 페이지] 레이아웃 구현
  fe/src/Manager/Manager.jsx
  fe/src/Manager/components/Sidebar.jsx
  fe/src/Manager/components/SidebarItem.jsx
  fe/src/Manager/components/Table.jsx
  fe/src/Manager/components/UserSearch.jsx
  fe/src/Manager/css/Manager.css
  fe/src/Manager/css/Sidebar.css
  fe/src/Manager/css/SidebarItem.css
  fe/src/Manager/css/Table.css
  fe/src/Manager/css/UserSearch.css
  fe/src/Manager/img/ID.png
  fe/src/Manager/img/no_img.png
  fe/src/Manager/img/search.png
  fe/src/Tech/Tech.jsx
  fe/src/components/css/Pagination.css
Labels: frontend

#71 라우터 적용
  fe/src/App.jsx
  fe/src/Layout/Layout.jsx
  fe/src/Main/Main.jsx
  fe/src/index.jsx
Labels: frontend

#78 [Write Page] CSS 반영
  fe/src/Write/CategorySelectBox.jsx
  fe/src/Write/Write.jsx
  fe/src/Write/css/CategorySelectBox.css
  fe/src/Write/css/HashtagInput.css
  fe/src/Write/css/TitleInput.css
  fe/src/Write/css/Write.css
Labels: frontend

#79 [Sign Up Page] CSS 반영 및 DOM 구조 변경
  fe/src/Login/css/LoginBox.css
  fe/src/SignUp/EmailStatus.jsx
  fe/src/SignUp/SignUpBox.jsx
  fe/src/SignUp/css/EmailStatus.css
  fe/src/SignUp/css/SignUpBox.css
  fe/src/SignUp/css/SignUpBtn.css
  fe/src/components/CardinalSelectBox.jsx
  fe/src/components/css/CardinalSelectBox.css
  fe/src/components/css/InputElement.css
Labels: frontend

#80 CSS 개선 및 DOM 구조 변경
  fe/src/Manager/components/Sidebar.jsx
  fe/src/Manager/components/SidebarItem.jsx
  fe/src/Manager/components/Table.jsx
  fe/src/Manager/css/Sidebar.css
  fe/src/Manager/css/SidebarItem.css
  fe/src/Manager/css/Table.css
  fe/src/Manager/img/ID.png
  fe/src/Manager/img/people.png
  fe/src/Manager/img/settings.png
  fe/src/Post/components/PostInfo.jsx
  fe/src/Post/css/Comment.css
  fe/src/Post/css/CommentBox.css
  fe/src/Post/css/Liked.css
  fe/src/Post/css/Post.css
  fe/src/Post/css/PostDesc.css
  fe/src/Post/css/PostInfo.css
  fe/src/Post/css/SelectBox.css
  fe/src/Post/img/post_more.png
  fe/src/components/css/Partition.css
  fe/src/components/css/PostDetails.css
Labels: frontend

#82 repository에서 data가 연결이 안 되는 문제 해결
  tcono/src/main/java/com/econovation/tcono/domain/heart/HeartRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/post/CategoryRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostRepository.java
  tcono/src/main/resources/graphql/schema.graphqls
Labels: backend

#85 Classname BEM 표기법으로 변경
  fe/src/Manager/Manager.jsx
  fe/src/Manager/components/Sidebar.jsx
  fe/src/Manager/components/SidebarItem.jsx
  fe/src/Manager/components/Table.jsx
  fe/src/Manager/components/UserSearch.jsx
  fe/src/Manager/css/Manager.css
  fe/src/Manager/css/Sidebar.css
  fe/src/Manager/css/SidebarItem.css
  fe/src/Manager/css/Table.css
  fe/src/Manager/css/UserSearch.css
  fe/src/Post/components/Comment.jsx
  fe/src/Post/components/CommentBox.jsx
  fe/src/Post/components/CommentList.jsx
  fe/src/Post/components/Liked.jsx
  fe/src/Post/components/PostInfo.jsx
  fe/src/Post/components/SelectBox.jsx
  fe/src/Post/components/Tags.jsx
  fe/src/Post/css/Comment.css
  fe/src/Post/css/CommentBox.css
  fe/src/Post/css/CommentList.css
  fe/src/Post/css/Liked.css
  fe/src/Post/css/PostInfo.css
  fe/src/Post/css/SelectBox.css
  fe/src/Post/css/Tags.css
  fe/src/Tech/Tech.jsx
  fe/src/Tech/components/Banner.jsx
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/css/Banner.css
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Recent.css
  fe/src/Tech/css/Tech.css
  fe/src/Tech/img/write.png
  fe/src/components/PostDetails.jsx
  fe/src/components/css/PostDetails.css
Labels: frontend

#86 PostCreateRequestDto : 변수명 변경
  tcono/src/main/java/com/econovation/tcono/domain/post/Post.java
  tcono/src/main/java/com/econovation/tcono/web/dto/PostCreateRequestDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/PostCreateResponseDto.java
  tcono/src/main/resources/graphql/.graphqlconfig
  tcono/src/main/resources/graphql/schema.graphqls
Labels: backend

#89 solve graphQL/HeartRepository , feat : post pagination
  tcono/build.gradle
  tcono/src/main/java/com/econovation/tcono/TestDataInit.java
  tcono/src/main/java/com/econovation/tcono/config/WebConfig.java
  tcono/src/main/java/com/econovation/tcono/domain/comment/CommentMutationResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/comment/CommentQueryResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/file/File.java
  tcono/src/main/java/com/econovation/tcono/domain/file/FileRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/heart/HeartMutationResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/heart/HeartRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/post/CategoryRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostMutationResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostQueryResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/user/User.java
  tcono/src/main/java/com/econovation/tcono/domain/user/UserRepository.java
  tcono/src/main/java/com/econovation/tcono/file/FileStore.java
  tcono/src/main/java/com/econovation/tcono/service/FileService.java
  tcono/src/main/java/com/econovation/tcono/service/UserService.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  tcono/src/main/java/com/econovation/tcono/web/dto/CommentCreateResponseDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/PostUpdateResponseDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UploadFile.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserCreateRequestDto.java
  tcono/src/main/resources/graphql/schema.graphqls
  tcono/src/test/java/com/econovation/tcono/post/PostResolverTest.java
  tcono/src/test/java/com/econovation/tcono/user/UserResolverTest.java
Labels: bug, backend

#88 [Header 및 ID 찾기 페이지] CSS 개선 및 디자인 변경사항 반영
  fe/src/FindID/FindID.jsx
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindID/FindIdBtn.jsx
  fe/src/FindID/css/FindID.css
  fe/src/FindID/css/FindIDBox.css
  fe/src/FindID/css/FindIdBtn.css
  fe/src/FindInfo/FindId.jsx
  fe/src/FindInfo/FindInfo.jsx
  fe/src/FindInfo/FindInfoBox.jsx
  fe/src/FindInfo/SuccessFindId.jsx
  fe/src/FindInfo/css/SuccessFindId.css
  fe/src/Header/Header.css
  fe/src/Header/Header.jsx
  fe/src/Header/components/NavItem.css
  fe/src/Header/components/NavItem.jsx
Labels: frontend

#90 부수적인 Route 작업 및 npm 설치
  fe/package-lock.json
  fe/package.json
  fe/src/Login/LoginBtn.jsx
  fe/src/Login/LoginLink.jsx
  fe/src/Login/SignUpLinkBtn.jsx
  fe/src/Write/Write.jsx
  fe/src/Write/css/Write.css
Labels: frontend

#91 [Header] Header 개선
  fe/src/Header/Header.jsx
  fe/src/Header/components/LoginButton.css
  fe/src/Header/components/LoginButton.jsx
  fe/src/Header/components/Search.css
  fe/src/Header/components/Search.jsx
  fe/src/Header/components/SearchInput.jsx
Labels: frontend

#92 docs : Dockerfile
  tcono/Dockerfile
Labels: documentation, backend

#95 feat : deploy code refactor
  tcono/Dockerfile
  tcono/src/main/java/com/econovation/tcono/config/WebConfig.java
  tcono/src/main/java/com/econovation/tcono/domain/user/User.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserCreateRequestDto.java
  tcono/src/main/resources/application.properties
Labels: bug, backend

#93 [MyPage] 내 정보 페이지 레이아웃 구현
  fe/src/MyPage/MyPage.jsx
  fe/src/MyPage/MyPosts.jsx
  fe/src/MyPage/Profile.jsx
  fe/src/MyPage/css/MyPage.css
  fe/src/MyPage/css/MyPosts.css
  fe/src/MyPage/css/Profile.css
Labels: frontend

#96 [관리자 페이지] 회원 정보 확인 레이아웃 추가 및 라우트 설정
  fe/src/Manager/Manager.jsx
  fe/src/Manager/components/PostList.jsx
  fe/src/Manager/components/SettingBox.jsx
  fe/src/Manager/components/Sidebar.jsx
  fe/src/Manager/components/SidebarItem.jsx
  fe/src/Manager/components/Table.jsx
  fe/src/Manager/components/UserInfo.jsx
  fe/src/Manager/components/UserList.jsx
  fe/src/Manager/css/Manager.css
  fe/src/Manager/css/PostList.css
  fe/src/Manager/css/SettingBox.css
  fe/src/Manager/css/SidebarItem.css
  fe/src/Manager/css/UserInfo.css
  fe/src/Manager/css/UserList.css
  fe/src/Post/Post.jsx
  fe/src/Post/components/Tags.jsx
  fe/src/Post/css/PostInfo.css
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/css/Official.css
  fe/src/Tech/css/Recent.css
  fe/src/Tech/css/Tags.css
  fe/src/Tech/css/Tech.css
  fe/src/components/Tags.jsx
  fe/src/components/css/Tags.css
Labels: frontend

#99 Post,Heart postman test
  tcono/src/main/java/com/econovation/tcono/domain/heart/Heart.java
  tcono/src/main/java/com/econovation/tcono/domain/heart/HeartMutationResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/heart/HeartRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/post/MainCategory.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostQueryResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostRepository.java
  tcono/src/main/java/com/econovation/tcono/web/dto/HeartRequestDto.java
Labels: backend

#101 feat : email LocalHost -> Server
  tcono/src/main/java/com/econovation/tcono/service/ConfirmationTokenService.java
Labels: backend, refactor

#98 [Search Page] 검색 페이지 레이아웃 구현
  fe/src/Search/Search.jsx
  fe/src/Search/components/SearchNavItem.jsx
  fe/src/Search/components/SearchResult.jsx
  fe/src/Search/components/TagSearch.jsx
  fe/src/Search/css/Search.css
  fe/src/Search/css/SearchNavItem.css
  fe/src/Search/css/SearchResult.css
  fe/src/Search/css/TagSearch.css
  fe/src/Search/img/search.png
Labels: frontend

#105 CSS 및 로직 리팩터링
  fe/package.json
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindID/FindIdBtn.jsx
  fe/src/FindID/css/FindIDBox.css
  fe/src/FindID/css/FindIdBtn.css
  fe/src/SignUp/SignUpBox.jsx
  fe/src/SignUp/components/SignUpBtn.jsx
  fe/src/SignUp/css/SignUpBox.css
  fe/src/SignUp/css/SignUpBtn.css
  fe/src/SignUp/util/VerifyPassword.jsx
  fe/src/components/CardinalSelectBox.jsx
Labels: frontend, refactor

#107 컴포넌트 추출, 제거 및 query 추가
  fe/src/Post/Post.jsx
  fe/src/Post/components/Liked.jsx
  fe/src/Post/components/PostInfo.jsx
  fe/src/Post/components/Title.jsx
  fe/src/Post/css/Title.css
  fe/src/Search/components/SearchResult.jsx
  fe/src/Tech/Tech.jsx
  fe/src/Tech/components/Official.jsx
  fe/src/Tech/components/Recent.jsx
  fe/src/Tech/css/Official.css
  fe/src/components/Partition.jsx
  fe/src/components/PostBox.jsx
  fe/src/components/PostDetails.jsx
  fe/src/components/css/Partition.css
  fe/src/components/css/PostBox.css
  fe/src/components/css/PostDetails.css
  fe/src/components/img/day.png
  fe/src/components/img/feather_eye.png
  fe/src/components/img/heart.png
  fe/src/components/img/no_img.png
  fe/src/components/img/select_bar.png
  fe/src/index.jsx
Labels: frontend

#111 feat : initData 빈객체 생성 오류 해결
  tcono/src/main/java/com/econovation/tcono/TestDataInit.java
  tcono/src/main/java/com/econovation/tcono/config/WebConfig.java
  tcono/src/main/java/com/econovation/tcono/domain/user/UserRepository.java
  tcono/src/main/java/com/econovation/tcono/service/UserService.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  test.mv.db
  test.trace.db
Labels: bug, backend

#113 Bug postId 타입 변경
  tcono/src/main/java/com/econovation/tcono/TestDataInit.java
  tcono/src/main/java/com/econovation/tcono/domain/post/Post.java
  tcono/src/main/resources/graphql/schema.graphqls
Labels: bug, backend

#118 total 카테고리가 특정 카테고리에 상관없이 모든 글 불러오도록 변경
  tcono/src/main/java/com/econovation/tcono/domain/post/PostQueryResolver.java
  tcono/src/main/java/com/econovation/tcono/domain/post/PostRepository.java
Labels: bug, backend

#116 로그인, 회원가입 POST 요청 및 아이디 & 비밀번호 찾기 페이지 레이아웃
  fe/package.json
  fe/src/App.js
  fe/src/App.jsx
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindID/SuccessFindId.jsx
  fe/src/FindID/css/FindIDBox.css
  fe/src/FindID/css/SuccessFindId.css
  fe/src/FindID/img/check_circle.png
  fe/src/FindPassword/FindPassword.css
  fe/src/FindPassword/FindPassword.jsx
  fe/src/Header/Header.css
  fe/src/Header/Header.jsx
  fe/src/Header/components/Search.css
  fe/src/Layout/Layout.css
  fe/src/Login/LoginBox.jsx
  fe/src/Login/LoginBtn.jsx
  fe/src/Login/css/LoginBox.css
  fe/src/Login/css/LoginBtn.css
  fe/src/Login/css/SignUpLinkBtn.css
  fe/src/NewPassword/NewPassword.css
  fe/src/NewPassword/NewPassword.jsx
  fe/src/SignUp/SignUpBox.jsx
  fe/src/components/CardinalSelectBox.jsx
  fe/src/components/css/InputElement.css
  tcono/.gitignore
  tcono/build.gradle
  tcono/gradle/wrapper/gradle-wrapper.jar
  tcono/gradle/wrapper/gradle-wrapper.properties
  tcono/gradlew
  tcono/gradlew.bat
  tcono/settings.gradle
  tcono/src/main/java/blog/econovation/tcono/TconoApplication.java
  tcono/src/main/java/blog/econovation/tcono/domain/BaseTimeEntity.java
  tcono/src/main/java/blog/econovation/tcono/domain/user/User.java
  tcono/src/main/java/blog/econovation/tcono/domain/user/UserMutationResolver.java
  tcono/src/main/java/blog/econovation/tcono/domain/user/UserQueryResolver.java
  tcono/src/main/resources/.graphqlconfig
  tcono/src/main/resources/application.properties
  tcono/src/main/resources/graphql/user/post.graphql
  tcono/src/test/java/blog/econovation/tcono/TconoApplicationTests.java
  tcono/src/test/java/blog/econovation/tcono/post/postControllerTest.java
Labels: frontend, refactor

#120 [관리자 페이지 & Post 페이지]
  fe/src/App.jsx
  fe/src/Footer/Footer.css
  fe/src/Footer/Footer.jsx
  fe/src/Manager/components/SettingBox.jsx
  fe/src/Manager/components/SidebarItem.jsx
  fe/src/Manager/components/UserInfo.jsx
  fe/src/Manager/components/UserList.jsx
  fe/src/Post/Post.jsx
  fe/src/Post/components/Liked.jsx
  fe/src/Post/components/PostInfo.jsx
  fe/src/Post/components/SelectBox.jsx
  fe/src/Post/css/Post.css
  fe/src/components/PostBox.jsx
  fe/src/components/PostDetails.jsx
Labels: frontend, refactor

#122 Find id 페이지 로직 구현
  fe/src/Context/LoginContext.jsx
  fe/src/FindID/FindID.jsx
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindID/SuccessFindId.jsx
  fe/src/FindInfo/img/check_circle.png
  fe/src/Header/Header.jsx
  fe/src/Login/LoginBox.jsx
  fe/src/Write/Write.jsx
  fe/src/index.jsx
Labels: frontend

#128 feat : 유저 수 세기, 특정 계급 유저 수 세기
  tcono/src/main/java/com/econovation/tcono/domain/user/UserRepository.java
  tcono/src/main/java/com/econovation/tcono/service/UserService.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  test.mv.db
  test.trace.db
Labels: backend

#127 [refactoring] 서버 로직 및 무결성 로직 개선
  fe/package-lock.json
  fe/package.json
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindPassword/FindPassword.css
  fe/src/Login/LoginBox.jsx
  fe/src/NewPassword/NewPassword.jsx
  fe/src/SignUp/SignUpBox.jsx
  fe/src/SignUp/css/SignUpBox.css
  fe/src/Write/Write.jsx
Labels: frontend, refactor

#130 bug : CORS Config -> Controller
  tcono/build.gradle
  tcono/src/main/java/com/econovation/tcono/config/WebConfig.java
  tcono/src/main/java/com/econovation/tcono/file/FileStore.java
  tcono/src/main/java/com/econovation/tcono/web/controller/FileController.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UploadPictureNameDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserCreateRequestDto.java
  tcono/src/main/resources/application.properties
  test.mv.db
  test.trace.db
Labels: bug, enhancement, backend, Epic, refactor

#129 서버 요청 로직 개선
  fe/package-lock.json
  fe/package.json
  fe/src/Context/LoginContext.jsx
  fe/src/FindID/FindIDBox.jsx
  fe/src/FindID/SuccessFindId.jsx
  fe/src/FindID/css/SuccessFindId.css
  fe/src/Header/Header.css
  fe/src/Header/Header.jsx
  fe/src/Login/LoginBox.jsx
  fe/src/MyPage/MyPage.jsx
  fe/src/MyPage/Profile.jsx
  fe/src/MyPage/css/Profile.css
  fe/src/SignUp/SignUpBox.jsx
  fe/src/Write/Write.jsx
Labels: bug, help wanted, frontend, refactor

#134 feat : Password 수정
  tcono/src/main/java/com/econovation/tcono/domain/file/FileRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/file/Picture.java
  tcono/src/main/java/com/econovation/tcono/domain/file/PictureRepository.java
  tcono/src/main/java/com/econovation/tcono/domain/user/User.java
  tcono/src/main/java/com/econovation/tcono/domain/user/UserRepository.java
  tcono/src/main/java/com/econovation/tcono/file/FileStore.java
  tcono/src/main/java/com/econovation/tcono/service/ConfirmationTokenService.java
  tcono/src/main/java/com/econovation/tcono/service/FileService.java
  tcono/src/main/java/com/econovation/tcono/service/UserService.java
  tcono/src/main/java/com/econovation/tcono/web/controller/FileController.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UploadFile.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UploadPictureNameDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserCreateRequestDto.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserPasswordUpdateDto.java
  tcono/src/main/resources/application.properties
  test.mv.db
Labels: documentation, enhancement, backend, refactor

#136 feat : Update -> ModelAttribute
  tcono/src/main/java/com/econovation/tcono/service/UserService.java
  tcono/src/main/java/com/econovation/tcono/web/controller/UserController.java
  tcono/src/main/java/com/econovation/tcono/web/dto/UserCreateRequestDto.java
  tcono/src/main/resources/application.properties
  test.mv.db
  test.trace.db
Labels: bug, backend, refactor
